---
defaults:
  timesteps_per_epoch: 1
  batch_size: 32
  total_steps: 10000
  decay_steps: 5000
  learning_rate: 1e-4
  init_epsilon: 1
  final_epsilon: 0.1
  refresh_target_network_freq: 100
  eval_freq: 1000
  gather_freq: 50
  replay_buffer_size: 10000
  train_episodes: 20000
  episode_max_timesteps: 1500
  grad_clip: 1
  loss: td

final_dqn_map_0:
  agent_id: DQN
  env_id: CartPole-v0
  config:
    total_steps :  40000
    decay_steps :  38000
    replay_buffer_size: 10000
    batch_size: 128
    refresh_target_network_freq :  1000
    hidden_layers:
      - 64
      - 64